#list.test:list_test.c
#	gcc -o list.test list_test.c
event.test:event_test.c ../src/simple_event_loop.c ../src/simple_event.c ../src/epoll.c
	gcc -o event.test event_test.c ../src/simple_event_loop.c ../src/simple_event.c ../src/epoll.c
